# DAY 1 - Mastering Data Pre-processing

In [3]:
# DAY 1 - Mastering Data Pre-processing
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/Users/aaron_green/Desktop/ML Pipeline/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading the dataset and visualizing

In [4]:
df = pd.read_csv('social_media_sleep_stress_productivity_11000.csv')
df.head()

,user_id,age,daily_screen_time_hours,social_media_hours,sleep_hours,exercise_minutes,study_work_hours,productivity_score,stress_level,platform
0,1,44,2.39,1.93,8.46,61,3.73,33.86,Low,YouTube
1,2,30,7.22,5.24,7.34,28,6.80,85.32,Low,YouTube
2,3,23,2.56,4.64,4.69,8,4.47,60.07,High,YouTube
3,4,36,8.75,4.89,5.05,53,9.53,36.46,Medium,LinkedIn
4,5,34,10.96,2.77,7.12,83,7.01,32.93,Medium,Instagram

In [5]:
df.info()
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  11000 non-null  int64
 1   age                      11000 non-null  int64
 2   daily_screen_time_hours  11000 non-null  float64
 3   social_media_hours       11000 non-null  float64
 4   sleep_hours              11000 non-null  float64
 5   exercise_minutes         11000 non-null  int64
 6   study_work_hours         11000 non-null  float64
 7   productivity_score       11000 non-null  float64
 8   stress_level             11000 non-null  str
 9   platform                 11000 non-null  str
dtypes: float64(5), int64(3), str(2)
memory usage: 859.5 KB
user_id                    0
age                        0
daily_screen_time_hours    0
social_media_hours         0
sleep_hours                0
exercise_minutes           0
study_work_hours           0
productivity_score         0
stress_level               0
platform                   0
dtype: int64

In [6]:
print(df.columns)
print(len(df))
print(df['age'])

Index(['user_id', 'age', 'daily_screen_time_hours', 'social_media_hours',
       'sleep_hours', 'exercise_minutes', 'study_work_hours',
       'productivity_score', 'stress_level', 'platform'],
      dtype='str')
11000
0        44
1        30
2        23
3        36
4        34
         ..
10995    27
10996    35
10997    38
10998    45
10999    45
Name: age, Length: 11000, dtype: int64

In [7]:
df['stress_level'] = df['stress_level'].map({'Low' : 1, 'Medium' : 2, 'High' : 3})

In [8]:
df['stress_level'].head()
df['stress_level'].isnull().sum()

np.int64(0)

In [9]:
df['stress_level'].unique()

array([1, 3, 2])

In [10]:
df['platform'].unique()

<StringArray>
['YouTube', 'LinkedIn', 'Instagram', 'Snapchat', 'Twitter']
Length: 5, dtype: str

In [11]:
print(f"original data for platform\n{df['platform']}\n")

df = pd.get_dummies(df, columns = ['platform'] )

original data for platform
0          YouTube
1          YouTube
2          YouTube
3         LinkedIn
4        Instagram
           ...
10995     LinkedIn
10996      YouTube
10997    Instagram
10998     Snapchat
10999      Twitter
Name: platform, Length: 11000, dtype: str

# Day 2 - Feature Engineering

In [12]:
df['social_media_ratio'] = df['social_media_hours'] / df['daily_screen_time_hours']
df['exercise_sleep_ratio'] = df['exercise_minutes'] / df['sleep_hours']

In [13]:
df.columns

Index(['user_id', 'age', 'daily_screen_time_hours', 'social_media_hours',
       'sleep_hours', 'exercise_minutes', 'study_work_hours',
       'productivity_score', 'stress_level', 'platform_Instagram',
       'platform_LinkedIn', 'platform_Snapchat', 'platform_Twitter',
       'platform_YouTube', 'social_media_ratio', 'exercise_sleep_ratio'],
      dtype='str')

In [18]:
print("Before creating features:")
print(df.columns)

df['social_media_ratio'] = df['social_media_hours'] / df['daily_screen_time_hours']
df['exercise_sleep_ratio'] = df['exercise_minutes'] / df['sleep_hours']

print("\nAfter creating features:")
print(df.columns)

print("\nCheck feature values:")
print(df[['exercise_sleep_ratio', 'social_media_ratio', 'productivity_score']].head())

print("\nCorrelation:")
print(df[['exercise_sleep_ratio', 'social_media_ratio', 'productivity_score']].corr())

Before creating features:
Index(['user_id', 'age', 'daily_screen_time_hours', 'social_media_hours',
       'sleep_hours', 'exercise_minutes', 'study_work_hours',
       'productivity_score', 'stress_level', 'platform_Instagram',
       'platform_LinkedIn', 'platform_Snapchat', 'platform_Twitter',
       'platform_YouTube', 'social_media_ratio', 'exercise_sleep_ratio'],
      dtype='str')

After creating features:
Index(['user_id', 'age', 'daily_screen_time_hours', 'social_media_hours',
       'sleep_hours', 'exercise_minutes', 'study_work_hours',
       'productivity_score', 'stress_level', 'platform_Instagram',
       'platform_LinkedIn', 'platform_Snapchat', 'platform_Twitter',
       'platform_YouTube', 'social_media_ratio', 'exercise_sleep_ratio'],
      dtype='str')

Check feature values:
   exercise_sleep_ratio  social_media_ratio  productivity_score
0              7.210402            0.807531               33.86
1              3.814714            0.725762               85.32
2              1.705757            1.812500               60.07
3             10.495050            0.558857               36.46
4             11.657303            0.252737               32.93

Correlation:
                      exercise_sleep_ratio  social_media_ratio  \
exercise_sleep_ratio              1.000000            0.002024
social_media_ratio                0.002024            1.000000
productivity_score               -0.010408           -0.001234

                      productivity_score
exercise_sleep_ratio           -0.010408
social_media_ratio             -0.001234
productivity_score              1.000000

In [15]:
df[['exercise_sleep_ratio','social_media_ratio']].isnull().sum()

exercise_sleep_ratio    0
social_media_ratio      0
dtype: int64

In [27]:
df['balance'] = df['study_work_hours'] - df['social_media_hours']
df['total_activity'] = (df['study_work_hours'] + df['exercise_minutes']) / 60

df[['total_activity', 'balance']].head()

                    balance  productivity_score
balance             1.00000             0.00228
productivity_score  0.00228             1.00000

In [29]:
# Correlation between total_activity, balance, and productivity_score
df[['total_activity', 'balance', 'productivity_score']].corr()

                    total_activity   balance  productivity_score
total_activity            1.000000  0.033305           -0.002101
balance                   0.033305  1.000000            0.002280
productivity_score       -0.002101  0.002280            1.000000

In [30]:
df.corr(numeric_only=True)

,user_id,age,daily_screen_time_hours,social_media_hours,sleep_hours,exercise_minutes,study_work_hours,productivity_score,stress_level,platform_Instagram,platform_LinkedIn,platform_Snapchat,platform_Twitter,platform_YouTube,social_media_ratio,exercise_sleep_ratio,balance,total_activity
user_id,1.000000,-0.011063,0.009036,-0.019142,0.005012,-0.017166,0.002703,-0.012438,0.000268,-0.010390,0.006907,0.005229,0.008489,-0.010390,-0.013145,-0.012704,0.014463,-0.016936
age,-0.011063,1.000000,0.010579,0.008645,0.014559,0.012698,0.007398,-0.011122,-0.021203,0.002822,0.002997,0.000720,-0.007480,0.000924,-0.008841,0.005035,0.000159,0.013229
daily_screen_time_hours,0.009036,0.010579,1.000000,0.009597,0.005060,0.012486,-0.011174,-0.002189,-0.009591,-0.004205,-0.008949,0.017537,0.008506,-0.012950,-0.635052,0.010740,-0.014874,0.011633
social_media_hours,-0.019142,0.008645,0.009597,1.000000,-0.006828,0.017897,0.019927,-0.005719,-0.007849,-0.004975,0.006280,-0.012992,0.005511,0.006179,0.491287,0.017161,-0.630479,0.019354
sleep_hours,0.005012,0.014559,0.005060,-0.006828,1.000000,0.007345,0.011542,0.015890,0.000039,0.000079,-0.001186,-0.004937,-0.006175,0.012239,0.001113,-0.444606,0.013372,0.008194
exercise_minutes,-0.017166,0.012698,0.012486,0.017897,0.007345,1.000000,-0.015583,-0.001968,-0.012236,0.009158,0.004593,-0.000787,-0.002545,-0.010361,0.002299,0.840187,-0.023658,0.997217
study_work_hours,0.002703,0.007398,-0.011174,0.019927,0.011542,-0.015583,1.000000,-0.001821,0.004658,-0.002365,-0.001172,0.001160,0.004806,-0.002437,0.020896,-0.016926,0.763489,0.059002
productivity_score,-0.012438,-0.011122,-0.002189,-0.005719,0.015890,-0.001968,-0.001821,1.000000,-0.004212,0.006307,-0.018296,-0.002991,0.015365,-0.000140,-0.001234,-0.010408,0.002280,-0.002101
stress_level,0.000268,-0.021203,-0.009591,-0.007849,0.000039,-0.012236,0.004658,-0.004212,1.000000,0.005804,0.002379,-0.005110,-0.000272,-0.002731,0.003146,-0.008735,0.008687,-0.011868
platform_Instagram,-0.010390,0.002822,-0.004205,-0.004975,0.000079,0.009158,-0.002365,0.006307,0.005804,1.000000,-0.248667,-0.248388,-0.244756,-0.245945,-0.008959,0.007632,0.001378,0.008967
platform_LinkedIn,0.006907,0.002997,-0.008949,0.006280,-0.001186,0.004593,-0.001172,-0.018296,0.002379,-0.248667,1.000000,-0.255278,-0.251546,-0.252767,0.007204,0.002233,-0.004967,0.004498
platform_Snapchat,0.005229,0.000720,0.017537,-0.012992,-0.004937,-0.000787,0.001160,-0.002991,-0.005110,-0.248388,-0.255278,1.000000,-0.251263,-0.252483,-0.017503,0.000135,0.009293,-0.000700
platform_Twitter,0.008489,-0.007480,0.008506,0.005511,-0.006175,-0.002545,0.004806,0.015365,-0.000272,-0.244756,-0.251546,-0.251263,1.000000,-0.248792,0.002540,-0.000656,0.000171,-0.002183
platform_YouTube,-0.010390,0.000924,-0.012950,0.006179,0.012239,-0.010361,-0.002437,-0.000140,-0.002731,-0.245945,-0.252767,-0.252483,-0.248792,1.000000,0.016693,-0.009286,-0.005883,-0.010526
social_media_ratio,-0.013145,-0.008841,-0.635052,0.491287,0.001113,0.002299,0.020896,-0.001234,0.003146,-0.008959,0.007204,-0.017503,0.002540,0.016693,1.000000,0.002024,-0.301124,0.003853
exercise_sleep_ratio,-0.012704,0.005035,0.010740,0.017161,-0.444606,0.840187,-0.016926,-0.010408,-0.008735,0.007632,0.002233,0.000135,-0.000656,-0.009286,0.002024,1.000000,-0.024226,0.837563
balance,0.014463,0.000159,-0.014874,-0.630479,0.013372,-0.023658,0.763489,0.002280,0.008687,0.001378,-0.004967,0.009293,0.000171,-0.005883,-0.301124,-0.024226,1.000000,0.033305
total_activity,-0.016936,0.013229,0.011633,0.019354,0.008194,0.997217,0.059002,-0.002101,-0.011868,0.008967,0.004498,-0.000700,-0.002183,-0.010526,0.003853,0.837563,0.033305,1.000000